### ISSUE TITLE
cannot to compile 

### ISSUE THREAD

**Issue by okbob** [adjust/pg_cryogen#1]
fix
<pre>
diff --git a/compression.h b/compression.h
index 7d875c5..865b7ce 100644
--- a/compression.h
+++ b/compression.h
@@ -10,17 +10,17 @@ typedef enum
     COMP_ZSTD
 } CompressionMethod;
 
-int compression_method_guc;
-int lz4_acceleration_guc;
-int zstd_compression_level_guc;
+extern int compression_method_guc;
+extern int lz4_acceleration_guc;
+extern int zstd_compression_level_guc;
 
-char *cryo_compress(CompressionMethod method,
+extern char *cryo_compress(CompressionMethod method,
                     const char *data,
                     Size *compressed_size);
-bool cryo_decompress(CompressionMethod method,
+extern bool cryo_decompress(CompressionMethod method,
                      const char *compressed,
                      Size compressed_size,
                      char *out);
-void cryo_define_compression_gucs(void);
+extern void cryo_define_compression_gucs(void);
 
 #endif /* __COMPRESSION_H__ */
</pre>

**Comment by zilder** [comment]
Hi @okbob,

Thanks a lot! Merged to master
