### ISSUE TITLE
cannot to compile pg_cryogen agaisnt Postgres 13

### ISSUE THREAD

**Issue by okbob** [adjust/pg_cryogen#3]
I cannot to compile this extension against master branch

**Comment by zilder** [comment]
Hi @okbob,

I hadn't tested it with master until now. I see lists implementation has changed significantly, they basically have been turned into vectors. Also i see some functions signatures changed. Overall shouldn't be hard to fix. Will do soon.

**Comment by zilder** [comment]
Fixed. @okbob can you please check that it works for you?

**Comment by okbob** [comment]
There is only a warning

include/libxml2   -c -o pg_cryogen.o pg_cryogen.c
pg_cryogen.c: In function ‘cryo_index_build_range_scan’:
pg_cryogen.c:1181:21: warning: unused variable ‘tuple’ [-Wunused-variable]
 1181 |         HeapTuple   tuple;

any other is ok

**Comment by zilder** [comment]
Fixed
